// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEyiCSXXiLv487B0e3e8iSzD-1bpoCnrw',
    appId: '1:104905051340:web:f703d58eb95cfb9c29c669',
    messagingSenderId: '104905051340',
    projectId: 'wellbeing-life',
    authDomain: 'wellbeing-life.firebaseapp.com',
    storageBucket: 'wellbeing-life.appspot.com',
    measurementId: 'G-3TCQWKCN6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj5jXwg3nYl7MsrG3xjU5P6QCRfXpIppM',
    appId: '1:104905051340:android:c73ae1b6a025243a29c669',
    messagingSenderId: '104905051340',
    projectId: 'wellbeing-life',
    storageBucket: 'wellbeing-life.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW7HdzH1crKhJNcL_1AQIJXKKbEs_0dAk',
    appId: '1:104905051340:ios:8af0a99bac19a4ee29c669',
    messagingSenderId: '104905051340',
    projectId: 'wellbeing-life',
    storageBucket: 'wellbeing-life.appspot.com',
    iosBundleId: 'com.example.wellbeingLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW7HdzH1crKhJNcL_1AQIJXKKbEs_0dAk',
    appId: '1:104905051340:ios:428f74878a11e7da29c669',
    messagingSenderId: '104905051340',
    projectId: 'wellbeing-life',
    storageBucket: 'wellbeing-life.appspot.com',
    iosBundleId: 'com.example.wellbeingLife.RunnerTests',
  );
}
